zip_download: https://github.com/causality/causal/zipball/
tar_download: https://github.com/causality/causal/tarball/
current_stable_version: 1.0.19
readme_link: https://github.com/causality/causal/wiki/Read-Me
